language: c

os:
- linux
- osx

compiler:
- gcc
- clang

env:
  global:
    # COVERITY_SCAN_TOKEN
    secure: "mmZHXvibHLB5EtpfO21JecaAT59qvIpNxt6h1+5KPkM9erCZ9OlBGL+fcpEcdmYXMakSCuweattTd943oawbK0fbZbRekicqj2P3NVq/egZyUoa0XC++d6aRmFeovJg4D7SpbBuR7xlnpUGsUco5qKT8rh9BWNt3Qc5NPIsx7q3va2lTTVc+18RLbXnsG/MwLhoARaSzeQYcW0FLGXwLqwOZG4q5HCKYQREWDUrlhsFIIWMHdZ8FeekPZTa0acKw3XErdqvpdZdpBsUVul0CiybNlCftJXVWH8W7N3WZTMCDtkGoKHsGbDOcmTaKw/Y2EXKciMdMpaS4FGw0N+MLYUeVeZWNWtcluWU4BIMCM4ZRk+YS2OPuQqcy45BsMN0f2eq1xbpdKvdXCEVDg5ipz4XwtC4lxrQYQEJ+lddSYWFDnbjGnTeuSbyvDx7hStpZIHsDrAAGdgTy0lGb4ul2p95xbUrVrDSVRq8gixJa/zq97EnYYEfz/lNJVxPOovxqOjR3JPg1xXWjXQM2gxAstPqmmkpjWRrIsmKQyaTOhYLNNPNtOwMCBzbDxQ0+9R6I7PGmF+uU/NaInPegvzvgCUrZd6DQ3E4T1UMFP4LwprKQ1vAw1epGw6gPKO+bUr3dhbccIdOY10KXyBmpnLzNX38eNURhxHNbDNNvDYOLDlU="

  matrix:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - BUILD_TYPE=MinSizeRel

addons:
  apt:
    packages:
    - libncurses5-dev
    - libncursesw5-dev
    - libxaw7-dev

  coverity_scan:
    project:
      name: "jwinarske/lpc21isp"
      description: "Build submitted via Travis CI"
    notification_email: joel.winarske@gmail.com
    build_command_prepend: mkdir build && cd build && cmake ..
    build_command: cmake --build . --target all
    branch_pattern: coverity_scan

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ${DEPS_DIR} && cd ${DEPS_DIR} && pwd; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_retry wget --no-check-certificate https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "96d67e21f0983ebf0fffc5b106ec338c *cmake-3.11.0-Linux-x86_64.tar.gz" > cmake_md5.txt; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then md5sum -c cmake_md5.txt; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvf cmake-3.11.0-Linux-x86_64.tar.gz > /dev/null; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv cmake-3.11.0-Linux-x86_64 cmake-install; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ncurses; fi

before_script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build && cd build
- cmake .. -DCMAKE_VERBOSE_MAKEFILE=FALSE -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/build/dist

script:
- cmake --build . --config ${BUILD_TYPE} --target install
