language: c
os:
- linux
- osx
compiler:
- gcc
- clang
env:
  matrix:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - BUILD_TYPE=MinSizeRel
  global:
    secure: 0MX0d2pPs9lU0jU/53DAFxAN2OucdNo/GMj4hwRWSjAXh9Thwu2Od4rbn2wb5gDHPG/QFZyU+NAKpNYqzS567WTK0n5rXL4dJ4Ch3msQiEMHzEnnU7YYb5ptPDOiWK9gbgcgYq2zfxu1k4k/VYNx72frBLBiuVsLWSfEldU44O3eKcnIJoiy7nh3HdctxFcj6q7xIf9GDo773otJsKEmfr54h/f6tESZQyzU5tOcCyPVOU69/4IMLtGNzdkpSXPVMASNIxJ1s3G882YR3FjFmcZ7fmooU0hd5XkAiYMxMKew0Ez8ssCmJNx7z0/u/Mj2lenRb9CLB9IvwjGkq/HbvirwkqlSngOWTVW1b9/hchfRvg/Ww8j3UETNak2FEw8G/bLgDiFBII3N7epcpjm4xa82H0UATCGbevkqP+FP9/T7t0b6nA6uifzKIye2W3ZB/1/aXPJCUY0n0RFQnrwavMulM7e78eNbG3+Vgs3JLFw+ncLit1yZUAjPh7EGGPprG2bYgzhHtfrzrq7Q4k0iJiqhjaVMRFwUxtMF9tN7hmToFawub1Ed5R7L5ucT7u0U0nizWgZTtrHxsbBWx3lt54zJ/dCLZQnCT5/0KU72Kw2b+P7kA7XTmz7IBR90RQ6umIhrZYeU4NUslwfkzO+PNp+Hg/jJSUjTxnS3ta4QI6Y=
addons:
  apt:
    packages:
    - libncurses5-dev
    - libncursesw5-dev
    - libxaw7-dev
  coverity_scan:
    project:
      name: “jwinarske/lpc21isp"
    notification_email: joel.winarske@gmail.com
    build_command_prepend: mkdir build && cd build && cmake -DDCMAKE_INSTALL_PREFIX=`pwd`/dist
      ..
    build_command: cmake --build . --target install
    branch_pattern: coverity_scan
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DEPS_DIR="${TRAVIS_BUILD_DIR}/deps";
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  && pwd; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_retry wget --no-check-certificate
  https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "96d67e21f0983ebf0fffc5b106ec338c
  *cmake-3.11.0-Linux-x86_64.tar.gz" > cmake_md5.txt; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then md5sum -c cmake_md5.txt; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvf cmake-3.11.0-Linux-x86_64.tar.gz
  > /dev/null; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv cmake-3.11.0-Linux-x86_64 cmake-install;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ncurses; fi
before_script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build && cd build
- cmake -DCMAKE_VERBOSE_MAKEFILE=FALSE -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/build/dist
  ..
script:
- cmake --build . --config ${BUILD_TYPE} --target install
